package Telas;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import model.Produtos_DAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author carlo
 */
public class Tela_Principal1 extends javax.swing.JFrame {   

    /**
     * Creates new form Tela_Inicial
     */
    public Tela_Principal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCooler = new javax.swing.JButton();
        btnFonte = new javax.swing.JButton();
        btnHdSSd = new javax.swing.JButton();
        btnMemoria = new javax.swing.JButton();
        btnMonitor = new javax.swing.JButton();
        btnMouse = new javax.swing.JButton();
        btnPlacaDeVideo = new javax.swing.JButton();
        btnPlacaMae = new javax.swing.JButton();
        btnProcessador = new javax.swing.JButton();
        btnTeclado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        btnComentarios = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        Painel_Produtos_Padrao = new javax.swing.JPanel();
        painel_promocoes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        painel_tabela = new javax.swing.JScrollPane();
        tabelaPromocoes = new javax.swing.JTable();
        lblNome3 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        lblRA3 = new javax.swing.JLabel();
        txtPreco1 = new javax.swing.JTextField();
        lblRA4 = new javax.swing.JLabel();
        txtQuantidade1 = new javax.swing.JTextField();
        lblNome4 = new javax.swing.JLabel();
        txtDescricao1 = new javax.swing.JTextField();
        lblRA5 = new javax.swing.JLabel();
        txtLoja1 = new javax.swing.JTextField();
        lblNome5 = new javax.swing.JLabel();
        txtCodp1 = new javax.swing.JTextField();
        btIncluirCarrinho1 = new javax.swing.JButton();
        Painel_Pesquisa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lblRA = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtCodp = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblNome1 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblRA1 = new javax.swing.JLabel();
        txtLoja = new javax.swing.JTextField();
        lblRA2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btIncluirCarrinho = new javax.swing.JButton();
        Painel_carrinho = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCarr = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Voltar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Comprar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cyber");

        Voltar.setBackground(new java.awt.Color(0, 51, 102));
        Voltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setText("Ofertas");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText(".COM");

        Sair.setBackground(new java.awt.Color(0, 51, 102));
        Sair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Olá, Cliente 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(368, 368, 368)
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Voltar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Sair)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        btnCooler.setBackground(new java.awt.Color(204, 204, 204));
        btnCooler.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCooler.setForeground(new java.awt.Color(0, 51, 102));
        btnCooler.setText("Cooler");
        btnCooler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCooler.setBorderPainted(false);
        btnCooler.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCooler.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btnCooler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoolerActionPerformed(evt);
            }
        });

        btnFonte.setBackground(new java.awt.Color(204, 204, 204));
        btnFonte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnFonte.setForeground(new java.awt.Color(0, 51, 102));
        btnFonte.setText("Fonte");
        btnFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFonteActionPerformed(evt);
            }
        });

        btnHdSSd.setBackground(new java.awt.Color(204, 204, 204));
        btnHdSSd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnHdSSd.setForeground(new java.awt.Color(0, 51, 102));
        btnHdSSd.setText("HD / SSD");
        btnHdSSd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHdSSdActionPerformed(evt);
            }
        });

        btnMemoria.setBackground(new java.awt.Color(204, 204, 204));
        btnMemoria.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMemoria.setForeground(new java.awt.Color(0, 51, 102));
        btnMemoria.setText("Memória");
        btnMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoriaActionPerformed(evt);
            }
        });

        btnMonitor.setBackground(new java.awt.Color(204, 204, 204));
        btnMonitor.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMonitor.setForeground(new java.awt.Color(0, 51, 102));
        btnMonitor.setText("Monitor");
        btnMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorActionPerformed(evt);
            }
        });

        btnMouse.setBackground(new java.awt.Color(204, 204, 204));
        btnMouse.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMouse.setForeground(new java.awt.Color(0, 51, 102));
        btnMouse.setText("Mouse");
        btnMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMouseActionPerformed(evt);
            }
        });

        btnPlacaDeVideo.setBackground(new java.awt.Color(204, 204, 204));
        btnPlacaDeVideo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPlacaDeVideo.setForeground(new java.awt.Color(0, 51, 102));
        btnPlacaDeVideo.setText("Placa de Vídeo");
        btnPlacaDeVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacaDeVideoActionPerformed(evt);
            }
        });

        btnPlacaMae.setBackground(new java.awt.Color(204, 204, 204));
        btnPlacaMae.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPlacaMae.setForeground(new java.awt.Color(0, 51, 102));
        btnPlacaMae.setText("Placa Mãe");
        btnPlacaMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacaMaeActionPerformed(evt);
            }
        });

        btnProcessador.setBackground(new java.awt.Color(204, 204, 204));
        btnProcessador.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnProcessador.setForeground(new java.awt.Color(0, 51, 102));
        btnProcessador.setText("Processador");
        btnProcessador.setBorderPainted(false);
        btnProcessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessadorActionPerformed(evt);
            }
        });

        btnTeclado.setBackground(new java.awt.Color(204, 204, 204));
        btnTeclado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnTeclado.setForeground(new java.awt.Color(0, 51, 102));
        btnTeclado.setText("Teclado");
        btnTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFonte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCooler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHdSSd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPlacaDeVideo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addComponent(btnPlacaMae, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProcessador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCooler, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHdSSd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlacaDeVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlacaMae, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cyber.COM Endereço: Av. Eng. Eusébio Stevaux, 823 Santo Amaro, São Paulo SP, 04696-000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton12.setBackground(new java.awt.Color(255, 153, 0));
        jButton12.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Meu Carrinho");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btnComentarios.setBackground(new java.awt.Color(255, 153, 0));
        btnComentarios.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnComentarios.setForeground(new java.awt.Color(255, 255, 255));
        btnComentarios.setText("Comentarios");
        btnComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentariosActionPerformed(evt);
            }
        });

        txtPesquisa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(255, 153, 51));
        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Buscar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        Painel_Produtos_Padrao.setLayout(new java.awt.CardLayout());

        painel_promocoes.setBackground(new java.awt.Color(224, 239, 253));

        jLabel6.setFont(new java.awt.Font("DejaVu Serif", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Todo dia ofertas incríveis ");

        jLabel7.setFont(new java.awt.Font("DejaVu Serif", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("só aqui no Cyber.");

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));

        jLabel8.setBackground(new java.awt.Color(0, 51, 102));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 53)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setText("OFERTAS DO DIA %");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("COM");

        painel_tabela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                painel_tabelaFocusGained(evt);
            }
        });
        painel_tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel_tabelaMouseClicked(evt);
            }
        });

        tabelaPromocoes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tabelaPromocoes.setForeground(new java.awt.Color(0, 51, 102));
        tabelaPromocoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "preco", "cod_P","nome","descricao","cod_L","qtde"
            }
        ));
        tabelaPromocoes.setRowHeight(26);
        tabelaPromocoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabelaPromocoesFocusGained(evt);
            }
        });
        tabelaPromocoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPromocoesMouseClicked(evt);
            }
        });
        painel_tabela.setViewportView(tabelaPromocoes);

        lblNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome3.setForeground(new java.awt.Color(0, 56, 102));
        lblNome3.setText("Nome");

        lblRA3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRA3.setForeground(new java.awt.Color(0, 56, 102));
        lblRA3.setText("Preço R$");

        txtPreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreco1ActionPerformed(evt);
            }
        });

        lblRA4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRA4.setForeground(new java.awt.Color(0, 56, 102));
        lblRA4.setText("Quantidade");

        txtQuantidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidade1ActionPerformed(evt);
            }
        });

        lblNome4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome4.setForeground(new java.awt.Color(0, 56, 102));
        lblNome4.setText("Descrição");

        lblRA5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRA5.setForeground(new java.awt.Color(0, 56, 102));
        lblRA5.setText("Codigo da Loja");

        txtLoja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoja1ActionPerformed(evt);
            }
        });

        lblNome5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome5.setForeground(new java.awt.Color(0, 56, 102));
        lblNome5.setText("Codigo do Produto");

        btIncluirCarrinho1.setBackground(new java.awt.Color(255, 153, 0));
        btIncluirCarrinho1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btIncluirCarrinho1.setForeground(new java.awt.Color(255, 255, 255));
        btIncluirCarrinho1.setText("Adicionar ao Carrinho");
        btIncluirCarrinho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirCarrinho1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_promocoesLayout = new javax.swing.GroupLayout(painel_promocoes);
        painel_promocoes.setLayout(painel_promocoesLayout);
        painel_promocoesLayout.setHorizontalGroup(
            painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_promocoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_promocoesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)
                        .addGap(17, 17, 17)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_promocoesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(painel_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painel_promocoesLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRA4)
                                .addGroup(painel_promocoesLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lblRA3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_promocoesLayout.createSequentialGroup()
                                    .addComponent(lblNome3)
                                    .addGap(17, 17, 17)))
                            .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNome1)
                                .addComponent(txtPreco1)
                                .addComponent(txtQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome5)
                                .addGroup(painel_promocoesLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(lblNome4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_promocoesLayout.createSequentialGroup()
                                    .addComponent(lblRA5)
                                    .addGap(16, 16, 16)))
                            .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(painel_promocoesLayout.createSequentialGroup()
                                    .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCodp1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                        .addComponent(txtLoja1))
                                    .addGap(18, 18, 18)
                                    .addComponent(btIncluirCarrinho1))
                                .addComponent(txtDescricao1))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        painel_promocoesLayout.setVerticalGroup(
            painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_promocoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_promocoesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_promocoesLayout.createSequentialGroup()
                    .addContainerGap(122, Short.MAX_VALUE)
                    .addComponent(painel_tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome3)
                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNome4)
                        .addComponent(txtDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painel_promocoesLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRA3)
                                    .addComponent(txtPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRA5)
                                    .addComponent(txtLoja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(painel_promocoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblRA4)
                                .addComponent(txtQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNome5)
                                .addComponent(txtCodp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(painel_promocoesLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(btIncluirCarrinho1)))
                    .addGap(23, 23, 23)))
        );

        Painel_Produtos_Padrao.add(painel_promocoes, "telap");

        tabela.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tabela.setForeground(new java.awt.Color(0, 51, 102));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "preco", "cod_P","nome","descricao","cod_L","qtde"
            }
        ));
        tabela.setRowHeight(26);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        lblRA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRA.setForeground(new java.awt.Color(0, 56, 102));
        lblRA.setText("Preço R$");

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 56, 102));
        lblNome.setText("Codigo do Produto");

        lblNome1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(0, 56, 102));
        lblNome1.setText("Nome");

        lblNome2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(0, 56, 102));
        lblNome2.setText("Descrição");

        lblRA1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRA1.setForeground(new java.awt.Color(0, 56, 102));
        lblRA1.setText("Codigo da Loja");

        txtLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLojaActionPerformed(evt);
            }
        });

        lblRA2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRA2.setForeground(new java.awt.Color(0, 56, 102));
        lblRA2.setText("Quantidade");

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        btIncluirCarrinho.setBackground(new java.awt.Color(255, 153, 0));
        btIncluirCarrinho.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btIncluirCarrinho.setForeground(new java.awt.Color(255, 255, 255));
        btIncluirCarrinho.setText("Adicionar ao Carrinho");
        btIncluirCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_PesquisaLayout = new javax.swing.GroupLayout(Painel_Pesquisa);
        Painel_Pesquisa.setLayout(Painel_PesquisaLayout);
        Painel_PesquisaLayout.setHorizontalGroup(
            Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRA2)
                            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblRA))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_PesquisaLayout.createSequentialGroup()
                                .addComponent(lblNome1)
                                .addGap(17, 17, 17)))
                        .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome)
                            .addComponent(txtPreco)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblNome2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_PesquisaLayout.createSequentialGroup()
                                .addComponent(lblRA1)
                                .addGap(16, 16, 16)))
                        .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodp, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(txtLoja))
                                .addGap(18, 18, 18)
                                .addComponent(btIncluirCarrinho))
                            .addComponent(txtDescricao))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_PesquisaLayout.setVerticalGroup(
            Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblRA)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblRA1)
                                .addComponent(txtLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRA2)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addComponent(txtCodp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btIncluirCarrinho)))
                .addGap(45, 45, 45))
        );

        Painel_Produtos_Padrao.add(Painel_Pesquisa, "tela1");

        tabelaCarr.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tabelaCarr.setForeground(new java.awt.Color(0, 51, 102));
        tabelaCarr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "preco", "cod_P","nome","descricao","cod_L","qtde"
            }
        ));
        jScrollPane2.setViewportView(tabelaCarr);

        jPanel8.setBackground(new java.awt.Color(0, 51, 102));
        jPanel8.setForeground(new java.awt.Color(0, 51, 102));

        jLabel13.setBackground(new java.awt.Color(255, 204, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Meu Carrinho");

        Voltar1.setBackground(new java.awt.Color(0, 51, 102));
        Voltar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Voltar1.setForeground(new java.awt.Color(255, 255, 255));
        Voltar1.setText("Voltar");
        Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Voltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(433, 433, 433))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Voltar1)
                        .addGap(53, 53, 53)))
                .addGap(27, 27, 27))
        );

        Comprar.setBackground(new java.awt.Color(204, 204, 204));
        Comprar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Comprar.setForeground(new java.awt.Color(0, 51, 102));
        Comprar.setText("Comprar Agora");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });

        Cancelar.setBackground(new java.awt.Color(204, 204, 204));
        Cancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(0, 51, 102));
        Cancelar.setText("Cancelar Compra");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(0, 51, 102));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("Esses produtos já são quase seus, após conferir, clique em comprar agora");

        btExcluir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(0, 51, 102));
        btExcluir.setText("Excluir Produto Selecionado");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_carrinhoLayout = new javax.swing.GroupLayout(Painel_carrinho);
        Painel_carrinho.setLayout(Painel_carrinhoLayout);
        Painel_carrinhoLayout.setHorizontalGroup(
            Painel_carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_carrinhoLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_carrinhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(52, 52, 52))
            .addGroup(Painel_carrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_carrinhoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_carrinhoLayout.createSequentialGroup()
                        .addComponent(Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        Painel_carrinhoLayout.setVerticalGroup(
            Painel_carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_carrinhoLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Painel_carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir))
                .addContainerGap())
        );

        Painel_Produtos_Padrao.add(Painel_carrinho, "telaCarrinho");

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Categorias");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Painel_Produtos_Padrao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPesquisa)
                        .addComponent(btnComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 47, Short.MAX_VALUE)
                        .addComponent(Painel_Produtos_Padrao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        new tela_de_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "telap");
    }//GEN-LAST:event_VoltarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentariosActionPerformed
        // TODO add your handling code here:
        new Tela_Comentarios().setVisible(true);
        dispose();        
    }//GEN-LAST:event_btnComentariosActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:       
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "telaCarrinho");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoriaActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto4()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnMemoriaActionPerformed

    private void btnCoolerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoolerActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto1()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnCoolerActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        String pesquisa = txtPesquisa.getText();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getPesquisa(pesquisa)) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecladoActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto10()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnTecladoActionPerformed

    private void btnFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFonteActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto2()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnFonteActionPerformed

    private void btnHdSSdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHdSSdActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto3()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnHdSSdActionPerformed

    private void btnMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto5()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnMonitorActionPerformed

    private void btnMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMouseActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto6()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnMouseActionPerformed

    private void btnPlacaDeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacaDeVideoActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto7()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnPlacaDeVideoActionPerformed

    private void btnPlacaMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacaMaeActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto8()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnPlacaMaeActionPerformed

    private void btnProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessadorActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getProduto9()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_btnProcessadorActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        int x = tabela.getSelectedRow();
        System.out.println(tabela.getValueAt(x, 0));
        txtPreco.setText(String.valueOf(tabela.getValueAt(x, 0)));
        txtCodp.setText(String.valueOf(tabela.getValueAt(x, 1)));
        txtNome.setText(String.valueOf(tabela.getValueAt(x, 2)));
        txtDescricao.setText(String.valueOf(tabela.getValueAt(x, 3)));
        txtLoja.setText(String.valueOf(tabela.getValueAt(x, 4)));
        txtQuantidade.setText(String.valueOf(tabela.getValueAt(x, 5)));
    }//GEN-LAST:event_tabelaMouseClicked

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLojaActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btIncluirCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirCarrinhoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tabelaCarr.getModel();
        modelo.addRow(new Object[]{txtPreco.getText(), txtCodp.getText(), txtNome.getText(), txtDescricao.getText(), txtLoja.getText(), txtQuantidade.getText()});
        JOptionPane.showMessageDialog(null, "Inserido no Carrinho.");
    }//GEN-LAST:event_btIncluirCarrinhoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int x = tabelaCarr.getSelectedRow();
        System.out.println(x);
        if (x != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tabelaCarr.getModel();
            modelo.removeRow(x);
        } else {
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar1ActionPerformed
        CardLayout cl = (CardLayout) Painel_Produtos_Padrao.getLayout();
        cl.show(Painel_Produtos_Padrao, "tela1");
    }//GEN-LAST:event_Voltar1ActionPerformed

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Comprado! você receberá os detalhes por e-mail.");
        new Tela_Principal1().setVisible(true);
        dispose();
    }//GEN-LAST:event_ComprarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        new Tela_Principal1().setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Comprado! você receberá os detalhes por e-mail.");
    }//GEN-LAST:event_CancelarActionPerformed

    private void tabelaPromocoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPromocoesMouseClicked
        // TODO add your handling code here:
        int x = tabelaPromocoes.getSelectedRow();
        System.out.println(tabelaPromocoes.getValueAt(x, 0));
        txtPreco1.setText(String.valueOf(tabelaPromocoes.getValueAt(x, 0)));
        txtCodp1.setText(String.valueOf(tabelaPromocoes.getValueAt(x, 1)));
        txtNome1.setText(String.valueOf(tabelaPromocoes.getValueAt(x, 2)));
        txtDescricao1.setText(String.valueOf(tabelaPromocoes.getValueAt(x, 3)));
        txtLoja1.setText(String.valueOf(tabelaPromocoes.getValueAt(x, 4)));
        txtQuantidade1.setText(String.valueOf(tabelaPromocoes.getValueAt(x, 5)));
    }//GEN-LAST:event_tabelaPromocoesMouseClicked

    private void txtPreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreco1ActionPerformed

    private void txtQuantidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidade1ActionPerformed

    private void txtLoja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoja1ActionPerformed

    private void btIncluirCarrinho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirCarrinho1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tabelaPromocoes.getModel();
        modelo.addRow(new Object[]{txtPreco1.getText(), txtCodp1.getText(), txtNome1.getText(), txtDescricao1.getText(), txtLoja1.getText(), txtQuantidade1.getText()});
        JOptionPane.showMessageDialog(null, "Inserido no Carrinho.");
    }//GEN-LAST:event_btIncluirCarrinho1ActionPerformed

    private void painel_tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_tabelaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_painel_tabelaMouseClicked

    private void painel_tabelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_painel_tabelaFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_painel_tabelaFocusGained

    private void tabelaPromocoesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaPromocoesFocusGained
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tabelaPromocoes.getModel();        
        modelo.setNumRows(0);
        Produtos_DAO dao = new Produtos_DAO();
        for (Produto c : dao.getPromocao()) {
            modelo.addRow(new Object[]{c.getpreco(), c.getcod_P(), c.getNome(), c.getdescricao(), c.getcod_L(), c.getqtde(),});
        }
    }//GEN-LAST:event_tabelaPromocoesFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Comprar;
    private javax.swing.JPanel Painel_Pesquisa;
    private javax.swing.JPanel Painel_Produtos_Padrao;
    private javax.swing.JPanel Painel_carrinho;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton Voltar1;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluirCarrinho;
    private javax.swing.JButton btIncluirCarrinho1;
    private javax.swing.JButton btnComentarios;
    private javax.swing.JButton btnCooler;
    private javax.swing.JButton btnFonte;
    private javax.swing.JButton btnHdSSd;
    private javax.swing.JButton btnMemoria;
    private javax.swing.JButton btnMonitor;
    private javax.swing.JButton btnMouse;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPlacaDeVideo;
    private javax.swing.JButton btnPlacaMae;
    private javax.swing.JButton btnProcessador;
    private javax.swing.JButton btnTeclado;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    private javax.swing.JLabel lblNome5;
    private javax.swing.JLabel lblRA;
    private javax.swing.JLabel lblRA1;
    private javax.swing.JLabel lblRA2;
    private javax.swing.JLabel lblRA3;
    private javax.swing.JLabel lblRA4;
    private javax.swing.JLabel lblRA5;
    private javax.swing.JPanel painel_promocoes;
    private javax.swing.JScrollPane painel_tabela;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaCarr;
    private javax.swing.JTable tabelaPromocoes;
    private javax.swing.JTextField txtCodp;
    private javax.swing.JTextField txtCodp1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricao1;
    private javax.swing.JTextField txtLoja;
    private javax.swing.JTextField txtLoja1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtPreco1;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtQuantidade1;
    // End of variables declaration//GEN-END:variables
}
